# archivo docker para postgresSQL
version: '3.8'

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: petrogassa-backend-container
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
