export enum Zones {
    AND = 'AL NORTE DE LA DORSAL',
    BASE = 'BASE CUTRAL CO',
    EMA = 'EL MANGRULLO',
    EL_PORTON = 'EL PORTON',
    EL_TRAPIAL = 'EL TRAPIAL',
    LLL = 'LOMA LA LATA',
    OFICINAS = 'OFICINA CUTRAL CO',
    PLANTA_ARENA = 'PLANTA ARENA',
    PLANTA_CENTENARIO = 'PLANTA CENTENARIO',
    REGIONAL_OESTE = 'REGIONAL OESTE',
    RDLS = 'RINCON DE LOS SAUCES',
    SCH = 'SIERRA CHATA',
    TEX = 'TURBO EXPANDER',
    ZC = 'ZONA CENTRAL'
}